### ISSUE TITLE
Allow iframes to be wider than the column 

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-cms#1370]
@kevinhowbrook, I'm starting a new issue for this, per our chat! Since we'll often embed maps and other more intricate iframes/dataviz, can we allow them to be wider than the standard width of a column? The default settings also right-align iframes, so if we allow them to be wider, the iframe should then also be centered on the page.

Would love to have this done by May 1, since one of the projects we're launching on that date has a world map that would be well-served by being larger. But if it takes a few extra days beyond that, that's OK. (Would also be curious what it would take to allow iframes to be full-width, if possible? But that's definitely more of a nice-to-have rather than something we need in the immediate term.)

**Comment by nmorduch** [comment]
I think the best option here might be to make a separate streamfield block for datawrapper embeds. The existing iframe block does something useful and fairly different from what datawrapper needs: it embeds a plain iframe with a consistent aspect ratio, where the datawrapper embed really would do best with the full markup that datawrapper provides for a responsive embed, within a wrapper that has the three width options of column, 1200px, and full width. (For what it's worth, I would be wary of a full-width option, because it could get very very big.)

In the long run, I would like to think about the best UI options for having a general embed block, where you then choose within it what type of content it has, which determines which set of fields it has (where some of the fields would change, and some of them, e.g. the fallback image, would stay the same). I think the main advantage of this over having separate blocks for each type of embed is simply that the number of types of blocks to choose from is getting very large.

@mariaelkin and @kevinhowbrook, opinions on this approach?

**Comment by mariaelkin** [comment]
As we just discussed, I think the approach you outlined makes sense!

**Comment by nmorduch** [comment]
Notes from conversations with @mariaelkin and @kevinhowbrook:

- Yes let's do a new block. Call it Datawrapper Embed, and have it something of a hybrid of the iframe and the image. I'll make it and have Kevin review.
- I need to check if I need to do things to make it work with Petey.
- I need to think about what fields it should have, and whether we want people to separate out pieces of the embed that Datawrapper can provide. I think we may want multiple fields, for title, description, and link.

**Comment by kevinhowbrook** [comment]
@nmorduch regarding rendering the block for pdf's, give me shout when you tackle this. It should just be a case of adding the block here in the pdf template https://github.com/newamericafoundation/newamerica-cms/blob/master/report/templates/report/pdf.html#L123
