### ISSUE TITLE
[2hrs] Syncing stage database with production

### ISSUE THREAD

**Issue by kevinhowbrook** [newamericafoundation/newamerica-cms#1401]
Hi @nmorduch just capturing this issue here, 

I'd suggest updating the stage database by downloading a backup from production and uploading it to staging as per the [heroku docs state](https://devcenter.heroku.com/articles/heroku-postgres-import-export) with the heroku cli, or is the request here to setup a sync task?

It's a good idea to configure a [fabric ](http://www.fabfile.org/) script to do this so it's easier going forward (we usually manage it this way). I think about 1 - 2 hours is enough time to configure that, this means we can sync staging with production on demand rather than a scheduled solution which may disrupt any current work in progress. 

Thanks

**Comment by nmorduch** [comment]
The task here is:
- configure a fabric script
- don't automatically move over all user accounts
  - is there a good way to maintain a specific set of user accounts?

**Comment by nmorduch** [comment]
DB definitely worked. Images didn't, or maybe I needed to wait longer?

I got this
```
Starting copy of DATABASE to DATABASE... done
Copying... done

```

and then nothing for a long time. not sure whether “Copying…” was the DB or an attempt at the media

I'm wondering if I can run this somewhere other than my local vm so that I don't have to worry about keeping my computer awake, or if that's probably not the problem
