### ISSUE TITLE
[0.75 hrs] Order editions of the Weekly more intentionally

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1424]
From @jacobtoppm in https://github.com/newamericafoundation/newamerica-cms/issues/1417#issuecomment-546908614
>I haven't changed how the latest edition is selected, aside from making it reject draft or private versions, as I didn't want to break any behaviour you're relying on. However, I've noticed that it doesn't have any ordering actually set in the query. While Wagtail's default ordering should grab the latest edition most of the time assuming you're adding them sequentially, this could potentially lead to problems if you update or re-publish an existing edition. Let me know if you would like me to add an ordering for you - either by the publication date or the edition number in the title.

@mariaelkin I'm thinking by edition number makes the most sense, yeah?

**Comment by nmorduch** [comment]
Maria says let's do by publication date! If it would be super quick to fit this in with the other change @jacobtoppm, we could do that, but this one's not urgent.

**Comment by jacobtoppm** [comment]
Sounds great, will get on that - just a quick query though: I just noticed that in the WeeklyList, the sorting is by edition number rather than publication date. So in that case if I make that change it's only the latest edition that would be found by publication date - is that what you'd like? (Alternatively, I can change all sorting to be by publication date - at the moment it's only the latest edition query that's unsorted).

**Comment by nmorduch** [comment]
Hm, let's hold off on this for now. I'd like to check that the publication dates will line up with the issue names, and this is a low priority.

**Comment by nmorduch** [comment]
Can you add an estimate, though?

**Comment by jacobtoppm** [comment]
This should be a relatively simple change, whichever way you decide to go - about 45 mins.

**Comment by nmorduch** [comment]
Obviated by #1455
