### ISSUE TITLE
Publications out of chronological order

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-cms#1449]
Publications in the main https://www.newamerica.org/publications/ list (and also in program publication lists https://www.newamerica.org/political-reform/publications/) are out of chronological order. 

I think this just happened within the last couple of days.

**Comment by nmorduch** [comment]
This happened yesterday as part of the fix Karl implemented; he needed a single unique field by which to order posts, and while the date of the post isn't unique, the time at which the post was first published is. The downside being that when the post was initially published is often well before the date of the post. @kaedroho what do you think of my proposed solution of having a calculated field that has a string that concatenates the date of the post and its id (or something like that)? And, in the mean time, is the a way to update the date first published field for a given important post? e.g. would setting the go live time do it?

**Comment by kaedroho** [comment]
@nmorduch Yep, I think your approach is the best one to use here. I think it would take around 2 hours to add that field, write a migration to populate it then update the API to use it.

**Comment by nmorduch** [comment]
@kaedroho do you think this is one it would make sense for me to take a shot at and ask for help if/when i get stuck? I think I'm getting much more confident about reading BE documentation

As far as I can tell I would:
- [ ] Make the field, which should be calculated on every save rather than input by people in the admin 
  - Add it to `Post`s: [home/models.py#L547-L653](https://github.com/newamericafoundation/newamerica-cms/blob/staging/home/models.py#L547-L653)
  - near the other calculated fields: [home/models.py#L634-L637](https://github.com/newamericafoundation/newamerica-cms/blob/staging/home/models.py#L634-L637)
  - concatenating `date` and `id` (not sure the Best way to do that in Python but can look into it, or pick one and you can tell me another one would be better)
  - For my reference: Docs re overriding save, though we're already doing that: [django docs: overriding model methods](https://docs.djangoproject.com/en/3.0/topics/db/models/#overriding-model-methods)
- [ ] Make a migration that doesn't just add that field but also calculates it for every post
  - This would be my first time writing a migration instead of just running `makemigrations`, so I should read that documentation ([django docs: migration files](https://docs.djangoproject.com/en/3.0/topics/migrations/#migration-files)) and maybe look at other human-written migrations we've had lately 
- [ ] Update the API to use that field like you did in https://github.com/newamericafoundation/newamerica-cms/commit/a7092d51053f8f6e98eb2fb8d4346582a093284d
- [ ] Try for ~15 minutes to figure out what I've inevitably done to break tests before asking you what I did

Am I correct that if it weren't for ordering we might do it as a `@property`, but you can't actually easily/efficiently order by those, which is why it's best to do it as a field?

**Comment by kaedroho** [comment]
Yep, I think you can give this one a shot!

> not sure the Best way to do that in Python but can look into it, or pick one and you can tell me another one would be better

I was thinking of using the date's `.isoformat()` and concatenating the ID to the end it. This should give a string that would give the correct ordering. For example, `2019-12-09-12345`

> Make a migration that doesn't just add that field but also calculates it for every post 

I'd create two separate migrations for this. PostgreSQL may give an error if you put schema changes and queries in the same migration (each migration runs in a transaction, so the schema changes aren't committed at the time the calculation is run).

Create the schema migration the usual way, then create an empty migration to put the calculation into using `makemigrations --empty <app name>`

> Am I correct that if it weren't for ordering we might do it as a @property, but you can't actually easily/efficiently order by those, which is why it's best to do it as a field?

Yep, making it a database field lets us use this field in queries, so we can ask the database to do the ordering/pagination and only fetch the results we need. Doing this would a property would mean we would have to pull all the posts into Python first which would be really slow.

**Comment by AnnaGrieve** [comment]
Naomi is picking this one up

**Comment by nmorduch** [comment]
Documentation re writing migrations to populate fields: https://docs.djangoproject.com/en/3.0/topics/migrations/#data-migrations
