### ISSUE TITLE
[1 hr] Weekly articles ordered incorrectly in Publications

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1475]
https://www.newamerica.org/publications/?after=2020-01-05&before=2020-01-16
https://www.newamerica.org/weekly-articles/?after=2019-12-01&before=2020-01-16

It's just the weekly articles from January, and they're getting sorted definitely after December ones, possibly after all publications

**Comment by kaedroho** [comment]
Looks like the issue is that weekly articles are bypassing the `Post.save()` method: https://github.com/newamericafoundation/newamerica-cms/blob/staging/weekly/models.py#L61

This means that the `ordered_date_string` field isn't being set. I'm not sure why this is being bypassed. All the logic except for setting `ordered_date_string` would be bypassed by Weekly articles.

So the solution would be to remove these two lines and run a script to populate this field for weekly articles.

**Comment by nmorduch** [comment]
Thanks! I can take this one then :)
