### ISSUE TITLE
[0.5hr investigation] Search pagination with page numbers

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1483]
~~Most importantly for search results.~~ Just on the search page.

 When you hit the back button after clicking on something in a list, you should get back to the same place. I don't have a strong preference between normal pagination and keeping the "load more" button (but with changing the url or something like that)

**Comment by AnnaGrieve** [comment]
Pagination as per Tumblr would be applied to search pages only

**Comment by AnnaGrieve** [comment]
Karl to spend half hour to estimate

**Comment by nmorduch** [comment]
An example of a tumblr url: https://www.tumblr.com/dashboard/2/190924265772
where 2 is the "page number" and "190924265772" is the post id. the page number part is fake but does let you go back a page. Not totally sure how the going back a page would work.

**Comment by kaedroho** [comment]
I can't find a way to get to the next page on Tumblr, it's just an infinite scroll for me. Also, there doesn't seem to be a way to leave that page without opening a new tab, all items open in a pop-up on the right for me so there isn't an issue with remembering the user's position.

So I'm thinking we want page based pagination so that users always go back to a page with just 10 or so results with one of them being the item they clicked, but implement this using cursor pagination for performance? This would be similar to Github's pagination (for example https://github.com/newamericafoundation/newamerica-cms/commits/staging?after=a0d7837e2c37af07fb35ee534ca3161f4a8d9740+34)
