### ISSUE TITLE
[2hr] Email sending isn't working for password resets and moderation requests

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1645]
I imagine it was set up at some point, but it doesn't work now.

**Comment by chigby** [comment]
Added `mailg.newamerica.org` to our production mailgun addon, then added the DNS settings, verified the domain, and changed the `POSTMARK_SENDER` heroku config variable to `no-reply@mailg.newamerica.org` (so that wagtail will use the new domain when sending.  Though I also think this variable name refers to a no-longer-used app Postmark).

**Comment by nmorduch** [comment]
This works now!
