### ISSUE TITLE
Editor - Image Focal Point

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#517]
Selecting a focal point didn't seem to work (I used the super vertical photo and tried to draw the focal point box around the cat's head). Also, when you save your edit of the image, you are automatically directed into the 'Images' page on Wagtail and have to navigate back to the page you were working on originally.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/115014319583031)

**Comment by rossvanderlinde** [comment]
I don't think we're currently using that feature. In fact I didn't even know about it. Either we should use it or try to remove from the editor to avoid confusion. Adding as a June issue

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
when editing an image in the editor, there is currently the ability to set the image's focal point.  We are not actually using this feature (primarily due to the fact that images are often included as background images throughout the site instead of img) so it has been flagged that it is confusing that it still exists as an option in the editor

**Comment by LomaxRx** [comment]
not able to remove focal point feature from wagtail editor
