### ISSUE TITLE
Links in short bios

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#740]
It looks like when there's a link in a short bio, it turns everything before it into a link to the full bio and everything after it isn't linked at all. Should we just not put links in the short bios?

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-05-09 at 10.35.27 AM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=131013020381703)
#url https://app.asana.com/0/0/131013020381700/f
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde Yeh, so as it is now, the entire author block for a given person links to that person's bio page.  When there is a link within the short bio though, it breaks the a tag that wraps around the author block, which is leading to the strange formatting.

I would say that short bios shouldn't have links - because of this issue, but also just because they are really meant to give someone the gist of full bio, not take them away from the site

If people are able to edit their own short bios, we should definitely make this clear to them though
