### ISSUE TITLE
Cant remove program affiliation for content

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#771]
I'm trying to remove the Future of War program affiliation for content, in order to move it to ISP and an initiative (rather than program) called Future of War.

When I remove Future of War program on here https://na-production.herokuapp.com/admin/pages/3558/edit/ it automatically re-adds it back :(

**Comment by sanajaved7** [comment]
@rossvanderlinde we can walk through on Google Hangouts how to do this but essentially you'll need to copy and move over the content with the "Move" function in Wagtail and then delete the existing program. There is a safeguard that tags programs if users don't remember to so I believe that's the issue here.
